// Mock leads matching the exact shape leadsService.js's _mapLead() returns.
// When you wire up the real service, swap MOCK_LEADS for
// window.leadsService.fetchLiveLeads(businessId) in useLeads.js — no
// component below needs to change, since every field name here is the
// same contract leadsService already produces.

export const MOCK_LEADS = [
  {
    id: 1,
    name: 'Wanjiru Kamau',
    phone: '+254712345678',
    lead_state: 'engaged',
    lead_type: 'business',
    lead_quality: 'hot',
    is_ad_lead: true,
    ad_id: 'ad_001',
    ad_platform: 'Meta',
    ad_headline: '30% off classic lash sets this week',
    ad_body: 'Book your classic lash set today and save 30%. Limited slots this week only.',
    ad_thumbnail_url: null,
    original_ad_id: null,
    unread_count: 2,
    last_seen: new Date(Date.now() - 12 * 60000).toISOString(),
    context_summary: 'Asking about classic lash set pricing and availability this Saturday',
    customer_intent: 'Wants a classic lash set booked for this Saturday',
    psychology: 'Price-sensitive but ready to commit if the slot is confirmed',
    conv_stage: 'Negotiating',
    follow_up_count: 1,
    product_interests: ['classic_lashes'],
    cart_state: ['Classic Lash Set'],
    trust_markers: ['Asked for location', 'Requested photos of past work'],
    vibe_check: 'Friendly and decisive once she has the facts — just needs a slot confirmed.',
    next_action_plan: 'Confirm Saturday 2pm slot and send the studio location pin.',
    product_sold: null,
    deal_value: null,
    purchase_date: null,
    is_business_chat: true,
    read_receipt: 'read',
    last_seen_online: new Date(Date.now() - 5 * 60000).toISOString(),
    sent_voice_note: false,
    sent_media: true,
    sent_reaction: false,
    intent_score: 82,
    competitor_mentions: ['Jumia'],
    objection_tags: ['price'],
    pre_purchase_questions: ['Do you do home visits?'],
    followup: {
      status: 'opted_in',
      current_step: 2,
      sent_steps: [1],
      pending_approval: true,
      draft: "Hi Wanjiru! Just checking in \u2014 loved catching up earlier. A few clients have asked about our classic lash sets this week and I thought of you. Saturday 2pm is still open if you'd like to lock it in \ud83d\udc9b",
      next_due: new Date(Date.now() + 2 * 3600000).toISOString(),
    },
    transcript: [],
  },
  {
    id: 2,
    name: 'Brian Otieno',
    phone: '+254722334455',
    lead_state: 'new',
    lead_type: 'business',
    lead_quality: 'warm',
    is_ad_lead: true,
    ad_id: 'ad_002',
    ad_platform: 'Meta',
    ad_headline: 'Volume lashes \u2014 book this week',
    ad_body: 'Full volume lash sets, done by our senior lash tech.',
    ad_thumbnail_url: null,
    original_ad_id: null,
    unread_count: 1,
    last_seen: new Date(Date.now() - 40 * 60000).toISOString(),
    context_summary: 'First message, asking how much volume lashes cost',
    customer_intent: 'Price check on volume lashes',
    psychology: '',
    conv_stage: 'New Lead',
    follow_up_count: 0,
    product_interests: ['volume_lashes'],
    cart_state: [],
    trust_markers: [],
    vibe_check: null,
    next_action_plan: 'Reply with pricing and ask what date works for them.',
    product_sold: null,
    deal_value: null,
    purchase_date: null,
    is_business_chat: true,
    read_receipt: 'delivered',
    last_seen_online: null,
    sent_voice_note: false,
    sent_media: false,
    sent_reaction: false,
    intent_score: 55,
    competitor_mentions: [],
    objection_tags: [],
    pre_purchase_questions: ['How much for volume lashes?'],
    followup: {
      status: 'not_enrolled',
      current_step: 0,
      sent_steps: [],
      pending_approval: false,
      draft: null,
      next_due: null,
    },
    transcript: [],
  },
  {
    id: 3,
    name: 'Faith Njeri',
    phone: '+254733112233',
    lead_state: 'stalled',
    lead_type: 'business',
    lead_quality: 'warm',
    is_ad_lead: false,
    ad_id: null,
    ad_platform: null,
    ad_headline: null,
    ad_body: null,
    ad_thumbnail_url: null,
    original_ad_id: null,
    unread_count: 0,
    last_seen: new Date(Date.now() - 4 * 24 * 3600000).toISOString(),
    context_summary: 'Was interested in a hybrid lash set, went quiet after asking about price',
    customer_intent: 'Hybrid lash set, budget-conscious',
    psychology: 'Went quiet right after the price was mentioned',
    conv_stage: 'Considering',
    follow_up_count: 3,
    product_interests: ['hybrid_lashes'],
    cart_state: ['Hybrid Lash Set'],
    trust_markers: [],
    vibe_check: 'Enthusiastic at first, cooled once price came up.',
    next_action_plan: 'Send a soft check-in \u2014 no pitch, just see if she is still interested.',
    product_sold: null,
    deal_value: null,
    purchase_date: null,
    is_business_chat: true,
    read_receipt: 'read',
    last_seen_online: new Date(Date.now() - 3 * 24 * 3600000).toISOString(),
    sent_voice_note: false,
    sent_media: false,
    sent_reaction: false,
    intent_score: 38,
    competitor_mentions: ['Jiji'],
    objection_tags: ['price', 'not_ready'],
    pre_purchase_questions: [],
    followup: {
      status: 'opted_in',
      current_step: 9,
      sent_steps: [1, 2, 3, 4, 5, 6, 7, 8],
      pending_approval: false,
      draft: null,
      next_due: new Date(Date.now() - 6 * 3600000).toISOString(),
    },
    transcript: [],
  },
  {
    id: 4,
    name: 'Dennis Mwangi',
    phone: '+254700998877',
    lead_state: 'won',
    lead_type: 'business',
    lead_quality: 'hot',
    is_ad_lead: true,
    ad_id: 'ad_003',
    ad_platform: 'Meta',
    ad_headline: 'Gift a lash set this weekend',
    ad_body: 'Surprise someone special with a full lash set voucher.',
    ad_thumbnail_url: null,
    original_ad_id: null,
    unread_count: 0,
    last_seen: new Date(Date.now() - 2 * 24 * 3600000).toISOString(),
    context_summary: 'Bought a gift voucher for his sister',
    customer_intent: 'Gift voucher purchase',
    psychology: '',
    conv_stage: 'Closed',
    follow_up_count: 2,
    product_interests: ['gift_voucher'],
    cart_state: [],
    trust_markers: ['Paid in full', 'Repeat customer'],
    vibe_check: null,
    next_action_plan: null,
    product_sold: 'Gift Voucher \u2014 Classic Set',
    deal_value: 3500,
    purchase_date: new Date(Date.now() - 2 * 24 * 3600000).toISOString(),
    is_business_chat: true,
    read_receipt: 'replied',
    last_seen_online: new Date(Date.now() - 1 * 24 * 3600000).toISOString(),
    sent_voice_note: false,
    sent_media: false,
    sent_reaction: true,
    intent_score: 91,
    competitor_mentions: [],
    objection_tags: [],
    pre_purchase_questions: [],
    followup: {
      status: 'completed',
      current_step: 11,
      sent_steps: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
      pending_approval: false,
      draft: null,
      next_due: null,
    },
    transcript: [],
  },
  {
    id: 5,
    name: 'Aisha Mohamed',
    phone: '+254711223344',
    lead_state: 'ghosted',
    lead_type: 'business',
    lead_quality: 'cold',
    is_ad_lead: false,
    ad_id: null,
    ad_platform: null,
    ad_headline: null,
    ad_body: null,
    ad_thumbnail_url: null,
    original_ad_id: null,
    unread_count: 0,
    last_seen: new Date(Date.now() - 20 * 24 * 3600000).toISOString(),
    context_summary: 'Asked about lash lifts once, never replied again',
    customer_intent: 'Lash lift inquiry',
    psychology: '',
    conv_stage: 'Cold',
    follow_up_count: 5,
    product_interests: ['lash_lift'],
    cart_state: [],
    trust_markers: [],
    vibe_check: null,
    next_action_plan: null,
    product_sold: null,
    deal_value: null,
    purchase_date: null,
    is_business_chat: true,
    read_receipt: 'sent',
    last_seen_online: null,
    sent_voice_note: false,
    sent_media: false,
    sent_reaction: false,
    intent_score: 12,
    competitor_mentions: [],
    objection_tags: ['not_ready'],
    pre_purchase_questions: [],
    followup: {
      status: 'opted_out',
      current_step: 5,
      sent_steps: [1, 2, 3, 4, 5],
      pending_approval: false,
      draft: null,
      next_due: null,
    },
    transcript: [],
  },
  {
    id: 6,
    name: 'Mama Shazz',
    phone: '+254799887766',
    lead_state: 'personal',
    lead_type: 'personal',
    lead_quality: 'warm',
    is_ad_lead: false,
    ad_id: null,
    ad_platform: null,
    ad_headline: null,
    ad_body: null,
    ad_thumbnail_url: null,
    original_ad_id: null,
    unread_count: 1,
    last_seen: new Date(Date.now() - 90 * 60000).toISOString(),
    context_summary: 'Family chat \u2014 not a customer conversation',
    customer_intent: '',
    psychology: '',
    conv_stage: 'New Lead',
    follow_up_count: 0,
    product_interests: [],
    cart_state: [],
    trust_markers: [],
    vibe_check: null,
    next_action_plan: null,
    product_sold: null,
    deal_value: null,
    purchase_date: null,
    is_business_chat: false,
    read_receipt: 'delivered',
    last_seen_online: null,
    sent_voice_note: true,
    sent_media: false,
    sent_reaction: false,
    intent_score: null,
    competitor_mentions: [],
    objection_tags: [],
    pre_purchase_questions: [],
    followup: {
      status: 'not_enrolled',
      current_step: 0,
      sent_steps: [],
      pending_approval: false,
      draft: null,
      next_due: null,
    },
    transcript: [],
  },
];